var myString = "heeeeey!";
var myNumber = 112;
var myBoolean = true;
var myAny = "Could be anything";
console.log(myString);
console.log(myNumber);
console.log(myBoolean);
console.log(myAny);
var stringArray = ["apple", "banana", "cherry"];
var numberArray = [1, 2, 3, 4, 5];
console.log(stringArray);
console.log(numberArray);
